import React from 'react';
import { Link } from 'react-router-dom';

const AboutPage: React.FC = () => {
  return (
    <div className="about-page">
      <section className="about-hero">
        <div className="container">
          <h1>About Our AI Textbook Platform</h1>
          <p>
            We're revolutionizing education through AI-powered textbook generation for Physical AI & Humanoid Robotics.
          </p>
        </div>
      </section>

      <section className="about-content">
        <div className="container">
          <div className="about-section">
            <h2>Our Mission</h2>
            <p>
              Our mission is to democratize access to high-quality educational content by leveraging artificial
              intelligence to create comprehensive, customizable textbooks for complex subjects like Physical AI
              and Humanoid Robotics. We believe that advanced educational tools should be accessible to everyone,
              everywhere.
            </p>
          </div>

          <div className="about-section">
            <h2>Technology Behind Our Platform</h2>
            <p>
              Our platform combines state-of-the-art language models with domain-specific knowledge bases to
              generate accurate, pedagogically sound content. We use advanced techniques in natural language
              processing, knowledge graph integration, and educational content modeling to create textbooks
              that meet the highest academic standards.
            </p>
          </div>

          <div className="about-section">
            <h2>Why Physical AI & Humanoid Robotics?</h2>
            <p>
              Physical AI and Humanoid Robotics represent the future of human-machine interaction. These fields
              require interdisciplinary knowledge spanning computer science, mechanical engineering, neuroscience,
              and cognitive science. Our platform helps educators and students navigate these complex topics with
              well-structured, comprehensive resources.
            </p>
          </div>

          <div className="about-section">
            <h2>Our Commitment to Quality</h2>
            <p>
              Every textbook generated by our platform undergoes rigorous content validation to ensure factual
              accuracy, ethical compliance, and pedagogical effectiveness. We work with domain experts to maintain
              the highest standards of educational content quality.
            </p>
          </div>
        </div>
      </section>

      <section className="cta-section">
        <div className="container">
          <h2>Ready to Transform Your Educational Experience?</h2>
          <p>Join thousands of educators and students using our platform to create and access high-quality textbooks.</p>
          <div className="cta-buttons">
            <Link to="/textbook/generate" className="btn btn-primary">Generate Textbook</Link>
            <Link to="/about" className="btn btn-secondary">Learn More</Link>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;